# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e04c3da59b8d7f93d761fd53a2564d48857b190119ed7d8f9a4bb3525cecf6d7409bced6b0b17945f138bae5b7fd08b017ac7fb44073144699f464b9b8c10d

test:
  secret_key_base: 33c7b1b735f2cd9e690beadbad29e46f7893f72aa7f85bcc9457338165783ecdb68e9f7058fd688afccc23dd0e57b8f6a0058ef2c28d00b5aea81edcc6b99e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
